### ISSUE TITLE
Expanding the clickable area

### ISSUE THREAD

**Issue by TindleWei** [Yalantis/FoldingTabBar.iOS#13]
The TabBar Buttons can only be clicked by the center images.
Sometimes it takes many invalid touches when trying to click the button. 
How to expand the clickable area？

**Comment by cminicus** [comment]
I had the same problem where it sometimes took several clicks for the bar buttons to register. I fixed this by going into YALFoldingTabBar.m and under the barItemDidTipped: method and commenting out the section that returns if self.isAnimated is true.

This made the buttons much more responsive for me since I did not have to wait for the animations to finish before they were interactive.

Hope this helps

**Comment by avicooper1** [comment]
This works perfectly. Thanks for the tip.

**Comment by avicooper1** [comment]
Is there a reason that these lines are included? (i.e. not just deleted in the master branch?) And if they are important, why can't it only return until the animation is mostly not done, but once its mostly done, i.e. 70% done, that it will no longer return?

**Comment by weinanfeng** [comment]
Flowers to @cminicus ! :bouquet:

**Comment by SandeepAggarwal** [comment]
Please fix this issue as @cminicus  pointed out, I don't find anything useful in keeping check on completion of animation of buttons.
